name: Copyright
run-name: Copyright
description: Updates license copyright year annually.
permissions: {}

on:
  schedule: # To update license copyright year annually on January 1st
    - cron: 0 0 1 1 *

jobs:
  license-copyright:
    name: Update license copyright year
    runs-on: ubuntu-latest

    permissions:
      contents: write # To update license file
      pull-requests: write # To create and merge pull request

    steps:
      - name: Checkout license file
        uses: actions/checkout@v6
        with:
          sparse-checkout: LICENSE
          persist-credentials: true
          sparse-checkout-cone-mode: false

      - name: Create pull request to update license copyright year
        id: update-license
        uses: FantasticFiasco/action-update-license-year@f180e962fa988db222d8f03ef4636750312d1b3d
        with:
          token: ${{ github.token }}
          labels: bot
          prTitle: Update license copyright year to {{currentYear}}
          branchName: github-action/update-license-year-to-{{currentYear}}
          commitTitle: "docs: update license copyright year"
          commitAuthorName: github-actions[bot]
          commitAuthorEmail: github-actions[bot]@users.noreply.github.com

      - name: Merge pull request
        if: ${{ steps.update-license.outputs.pullRequestNumber != '' }}
        run: gh pr merge $PULL_REQUEST_NUMBER --admin --merge --delete-branch
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PULL_REQUEST_NUMBER: ${{ steps.update-license.outputs.pullRequestNumber }}

concurrency:
  group: copyright
  cancel-in-progress: true
